export {
  CALCULATORS,
  PLACEHOLDERS,
  BUTTONS,
  LABELS,
  IDS,
  INPUT_TYPE,
  COLORS,
  CALC_LABELS,
  LATEX,
} from "./constants";

export {
  AREA_CALCULATORS,
  SURFACEAREA_CALCULATORS,
  VOLUME_CALCULATORS,
  DUE_DATE_CALCULATORS,
  CONCRETE_CALCULATORS,
} from "./calculatorNames";

export {
  GEOMETRY_PLACEHOLDERS,
  STATISTICS_PLACEHOLDERS,
  FRACTION_PLACEHOLDERS,
  GENERAL_PLACEHOLDERS,
  ALGEBRA_PLACEHOLDERS,
  INVESTMENT_AND_SAVINGS_PLACEHOLDERS,
  MONEY_PLACEHOLDERS,
  LOAN_PLACEHOLDERS,
  RETIREMENT_PLACEHOLDERS,
  SALES_PLACEHOLDERS,
  FITNESS_PLACEHOLDERS,
  HEALTH_PLACEHOLDERS,
  TIME_PLACEHOLDERS,
  TECHNOLOGY_PLACEHOLDERS,
  TRANSPORT_PLACEHOLDERS,
  MEASURMENT_PLACEHOLDERS,
  UNIT_CONVERSION_PLACEHOLDERS,
  ELECTRONICS_OR_CIRCUITS_PLACEHOLDERS,
  HOUSING_OR_BUILDINGS_PLACEHOLDERS,
} from './placeholderText'